package by.epam.lobanok.controller.command;

public enum CommandName {
	ENTRANCE, 
	REGISTRATION,
	LOCALIZATION,
	GO_TO_REGISTRATION_PAGE, 	
	GO_TO_MAIN_PAGE, 
	GO_TO_COURSES_PAGE,
	GO_TO_RUNNING_COURSES_PAGE,
	GO_TO_ABOUT_PAGE,
	
	GO_TO_USER_PAGE, 
	GO_TO_USER_COURSES_PAGE,
	GO_TO_USER_COURSE_RESULT_PAGE;
}