package by.epam.lobanok.controller.command;

public enum CommandName {
	ENTRANCE, REGISTRATION, GO_TO_REGISTRATION_PAGE, LOCALIZATION,
	GO_TO_MAIN_PAGE, GO_TO_COURSES_PAGE, GO_TO_ABOUT_PAGE,
	GO_TO_USER_PAGE, GO_TO_USER_COURSES_PAGE;
}