package by.epam.lobanok.controller.command;

public enum CommandName {
	ENTRANCE, 
	REGISTRATION,
	EDIT_PROFILE,
	LOCALIZATION,
	EXIT,
	
	GO_TO_REGISTRATION_PAGE, 	
	GO_TO_MAIN_PAGE, 
	GO_TO_COURSES_PAGE,
	GO_TO_RUNNING_COURSES_PAGE,
	GO_TO_ABOUT_PAGE,
	
	GO_TO_USER_PAGE, 
	GO_TO_EDIT_PROFILE,
	GO_TO_USER_COURSES_PAGE,
	
	GO_TO_STUDENT_COURSE_RESULT_PAGE,
	GO_TO_STUDENT_COURSES_RESULTS_PAGE,
	ADD_COURSE_PARTICIPANT,
	DELETE_COURSE_PARTICIPANT,
	
	GO_TO_TEACHER_COURSE_PARTICIPANTS_PAGE,
	ADD_COURSE_RESULT,
	
	GO_TO_ALL_TEACHERS_PAGE,
	GO_TO_ALL_STUDENTS_PAGE,
	
	GO_TO_EDIT_COURSE_PAGE,
	EDIT_COURSE,
	GO_TO_ADD_COURSE_PAGE,
	ADD_COURSE,
	
	GO_TO_EDIT_RUNNING_COURSE_PAGE,
	EDIT_RUNNING_COURSE,
	GO_TO_ADD_RUNNING_COURSE_PAGE,
	ADD_RUNNING_COURSE,	
}